### ISSUE TITLE
Merge Manifest.xml instead override it

### ISSUE THREAD

**Issue by sjvc** [Over17/UnityAndroidPermissions#1]
Hi!

If you use the Manifest.xml as you suggest, then this Manifest.xml will override the Unity Manifest.xml. It would be better to merge it instead. To do it, just add "unityplayer.SkipPermissionsDialog"="true" metadata tag to the Manifest.xml in src folder, so it will be inside aar, and it will be merged and such tag will appear on the Manifest.mxl generated by Unity.

Thanks for this great plugin!

**Comment by Over17** [comment]
@sjvc for some reason I was pretty sure the manifest merger is going to fail in this case. However it works with both v1 and v2 manifmerger! Fix pushed - now the plugin is even greater because it doesn't need the manifest magic ;)

Thanks for reporting this!

**Comment by Over17** [comment]
Resolved in v0.2
