### ISSUE TITLE
ANRs And crashes

### ISSUE THREAD

**Issue by karanvariya** [Over17/UnityAndroidPermissions#11]
![capture](https://user-images.githubusercontent.com/36916495/40637871-7460c4a8-6325-11e8-8bef-8a9f0969c32b.PNG)

See ANRs Report of my game after using this plugin. ANRs is high.please give me solution.

**Comment by Over17** [comment]
Sorry I can't help you with the data you've provided here. Please conduct your own investigation and feel free to get back once you have more details on what is happening where.
