### ISSUE TITLE
Denied Permission

### ISSUE THREAD

**Issue by mrm83** [Over17/UnityAndroidPermissions#12]
I am using unity 5.3.4 and am trying to implement this to fix the OREO black screen issue.

I created a blank scene and added the library and implemented the sample code.

I am checking to see if the storage permission is granted, if not i immediately call the grant button press function (so i don't have to create a ui.. for testing only) however the callback comes back as failed.

Am i missing something or doing something wrong?

**Comment by Over17** [comment]
I think you can't automate this dialog as it's displayed by system, and also security critical.
If you want to automate permission granting, you may want to use adb shell pm grant or adb install -g. Please refer to adb documentation/help for more details.

**Comment by mrm83** [comment]
I updated the scene:

The function is called when my UI button is clicked, same thing..  the failed callback is returned.

**Comment by Over17** [comment]
Sorry I have little idea of what you are talking. Your setup is most likely incorrect.
