### ISSUE TITLE
com.unity3d.plugin.UnityAndroidPermissions$IPermissionRequestResult2 ClassNotFoundException

### ISSUE THREAD

**Issue by JackM36** [Over17/UnityAndroidPermissions#17]
Hello,

I tried to use this, but I get this error:

```
AndroidJavaException: java.lang.ClassNotFoundException: com.unity3d.plugin.UnityAndroidPermissions$IPermissionRequestResult2
10-31 14:53:40.712  7396  7411 E Unity   : java.lang.ClassNotFoundException: com.unity3d.plugin.UnityAndroidPermissions$IPermissionRequestResult2
10-31 14:53:40.712  7396  7411 E Unity   :      at java.lang.Class.classForName(Native Method)
10-31 14:53:40.712  7396  7411 E Unity   :      at java.lang.Class.forName(Class.java:400)
10-31 14:53:40.712  7396  7411 E Unity   :      at java.lang.Class.forName(Class.java:326)
10-31 14:53:40.712  7396  7411 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
10-31 14:53:40.712  7396  7411 E Unity   :      at com.unity3d.player.UnityPlayer.c(Unknown Source)
10-31 14:53:40.712  7396  7411 E Unity   :      at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source)
10-31 14:53:40.712  7396  7411 E Unity   :      at android.os.MessageQueue.next(MessageQueue.java:392)
10-31 14:53:40.712  7396  7411 E Unity   :      at android.os.Looper.loop(Looper.java:136)
10-31 14:53:40.712  7396  7411 E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source)
10-31 14:53:40.712  7396  7411 E Unity   : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.unity3d.plugin.UnityAndroidPermissions$IPermissionRequestResult2" on path: DexPathList[[zip file "/data/app/com.vrhouse.ez360-1/base.apk"],nativeLibraryDirectories=[/data/app/com.vrhouse.ez360-1/lib/arm, /data/app/com.vrhouse.ez360-1/base.apk!/lib/armea
10-31 14:53:41.423  7396  7421 E Unity   : java.net.UnknownHostException: Unable to resolve host "config.uca.cloud.unity3d.com": No address associated with hostname
```

Any idea how to fix it?

**Comment by Over17** [comment]
Hi!

Looks like I forgot to update the .aar in the Unity project here.
Fixed in https://github.com/Over17/UnityAndroidPermissions/commit/d31bc86b79a3b6a9b47c85557d62ad4a35af308c - can you pull, update the aar in your project and see if it works?

Thanks for reporting it!

**Comment by Over17** [comment]
No answer, should be fixed.

**Comment by phuzik** [comment]
New aar not working.

`03-24 13:12:30.970 26908 26994 I Unity   :   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0 
03-24 13:12:30.970 26908 26994 I Unity   :   at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (IntPtr clazz, IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <filename unknown>:0 
03-24 13:12:30.970 26908 26994 I Unity   :   at UnityEngine.AndroidJavaObject._CallStatic[AndroidJavaObject] (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0 
03-24 13:12:30.970 26908 26994 I Unity   :   at UnityEngine.AndroidJavaObject.CallStatic[AndroidJavaObject] (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0 
03-24 13:12:30.970 26908 26994 I Unity   :   at UnityEngine.AndroidJavaObject.FindClass (System.String name) [0x00000] in <filename unknown>:0 
03-24 13:12:30.970 26908 26994 I Unity   :   at UnityEngine.AndroidJavaObject._AndroidJavaObject (System.String className, System.Object[] args) [0x00000] in <filename unknown>:0 
03-24 13:12:30.970 26908 26994 I Unity   :   at UnityEngine.AndroidJavaObject..ctor (System.String className, System.Object[] args) [0x00000] in <filename unknown>:0 
03-24 13:12:30.970 26908 26994 I Unity   :   at AndroidPermissionsManage`
