### ISSUE TITLE
Android UI Dialog Doesn't Show Up

### ISSUE THREAD

**Issue by DanhuaZhang** [Over17/UnityAndroidPermissions#19]
Not sure if this is because of Unity or Oculus Quest, The problem is, the android UI dialog doesn't show up. The Unity version I'm using is 2019.4.11.

What I have done is:
1. Copied and pasted the unityandroidpermissions.aar file under Assets/Plugins/Android (tried both the downloaded version and the one I built by myself);
2. Changed the path of the .aar file to Assets/Plugins/Android/**libs**, as this is from the manual doc of Unity 2019.4;
2. Set "unityplayer.SkipPermissionsDialog" to true in the "AndroidManifest.xml" file (otherwise it'd conflict with the .aar file);
3. Attached the AndroidPermissionsUsageExample.cs to an empty GameObject in my scene;
4. Built to the Android device (I'm using Oculus Quest).

Is there any step I did wrong or I missed some configuration?

**Comment by Over17** [comment]
It might be Quest is blocking the UI, but quick internet search says it should work.

Simple debugging steps that immediately come to my mind:
- what's in the logcat?
- did you forget to declare the permissions in the manifest?
- can you try adding a Debug.Log() into the AndroidPermissionsUsageExample script and see if you get the entry in logcat?

**Comment by DanhuaZhang** [comment]
I was using exactly the sample script and didn't change anything, but I added Debug.log() functions to 41, 44 and 49 line in the "AndroidPermissionsUsageExample.cs" script file to check out "grantedPermission", "deniedPermission" and "deniedPermissionAndDontAskAgain".  [https://github.com/Over17/UnityAndroidPermissions/blob/master/Assets/Scripts/AndroidPermissionsUsageExample.cs](https://github.com/Over17/UnityAndroidPermissions/blob/master/Assets/Scripts/AndroidPermissionsUsageExample.cs)
1. The logcat didn't print anything from Debug.log() functions, but execute line 14 Debug.LogWarning: Missing permission to browse device gallery, please grant the permission first. While no Android UI Window showed up after the app started.
2. Not sure if this is what you were referring to, as I said, I set **unityplayer.SkipPermissionsDialog** to **true** in both the "AndroidManifest.xml" file and "AndroidManifest.xml.DISABLED".
3. I don't know what "entry" means, but the script didn't print anything from the "AndroidPermissionsUsageExample.cs" except the warning message.

**Comment by Over17** [comment]
"entry" in this case means "a line in the log".
Okay so the permission is _not_ granted.

> did you forget to declare the permissions in the manifest?

Did you declare the `android.permission.READ_EXTERNAL_STORAGE` permission in the manifest?
`<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>`

**Comment by DanhuaZhang** [comment]
Great catch! I forgot to add it, and it works now after I declared it! Sorry that I'm not familiar with Android development and wasted your time. Thanks a lot! Great work and really appreciate it! Sorry again for your time.
