### ISSUE TITLE
MainThread issue

### ISSUE THREAD

**Issue by Nyankoo** [Over17/UnityAndroidPermissions#6]
@Over17 
I'm calling an event in the callback of "AndroidPermissionsManager.RequestPermission" and the attached method of the event listener calls "Destroy(myGameObject)".

The "Destroy()" line causes a UnityException, that this can only be called from the main thread. I'm not using other threads anywhere, so I was wondering if the callback is automatically executed on another thread.

**Comment by Nyankoo** [comment]
@Over17 Any info on this?

**Comment by yasirkula** [comment]
This might help you: https://github.com/PimDeWitte/UnityMainThreadDispatcher

**Comment by Nyankoo** [comment]
@yasirkula 
Thank you for the link, but this is not really answering my question of the Permission Manager is executed on a different thread.

**Comment by Over17** [comment]
@Nyankoo AndroidPermissionsManager is implemented using Unity's AndroidJavaProxy. It receives a callback on the thread that invoked it, in this case it's the Java UI thread (which is not the same as Unity UI thread).

If you want to run something on the Unity UI thread, you'll have to use some sort of synchronization and signal it from the callback.

More reads:
https://answers.unity.com/questions/854901/android-plugins-that-raise-callbacks-on-non-script.html
https://stackoverflow.com/questions/38001946/android-os6-runtime-permissions-callback-thread-for-onrequestpermissionsresul/38001971#38001971

**Comment by Nyankoo** [comment]
@Over17 Thank you for the explanation!
Shouldn't that be mentioned somewhere in the example code or the description of the plugin?
I'm calling the methods from the UI thread and it's somewhat not intuitive that the callback is triggered on some other thread.

**Comment by Over17** [comment]
I'll update README.

**Comment by Over17** [comment]
Fixed in d6be34e2f43d2ea8ad9d61cbe4ff8cb4b0fd5455.
