### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by MyOwnClone** [Over17/UnityAndroidPermissions#7]
Hi, thanks for the great plugin and hard work, but so far, I have been unable to get it working properly. 
Maybe I am just completely misunderstanding the stuff and kind of expecting something which the plugin doesn't provide, in this case, I do apologize in advance.

Now, to the problem. I am using or trying to use 
`void RequestPermission()` for a `android.permission.WRITE_EXTERNAL_STORAGE`.
If I understand correctly, this method, when invoked, should request the given permission from the user by showing some system dialog and calling appropriate callback afterwards. But when I call this method, no system UI is shown and `OnPermissionDenied()` is immediately called indicating that permission has been denied.

Is this the expected behavior? Am I doing something wrong or did I understand the docs the wrong way?

**Comment by Over17** [comment]
Hi!

I have few assumptions why it didn't work for you:
1. The permission is not present in your AndroidManifest.xml. Examine it either in Temp/StagingArea right after building or use Android Studio APK Analyzer.
2. You have denied the permission previously and checked "don't ask me again". In that case, go to Settings - Apps - YourApp - Permissions and check it out.

Anyway, checking logcat is a good idea. 1) should have a clear message there.

**Comment by MyOwnClone** [comment]
Thanks! Adding the permission did the trick! To be precise, the permission was already in our AndroidManifest.xml but it was limited to maxSdkVersion 18, so it did not apply to newer SDK versions, which was exactly the problem. Thanks again!

**Comment by Over17** [comment]
Great!
